{spawn,exec} = require 'child_process'

launch = (cmd, options=[], callback) ->
	app = spawn cmd, options, (err) ->
		console.log err
	app.stdout.pipe(process.stdout)
	app.stderr.pipe(process.stderr)
	app.on 'exit', (status) -> callback?() if status is 0

launch2 = (cmd, callback) ->
	[x,y...] = cmd.split(' ')
	launch x,y,callback


task 'sbuild', 'ho!', ->
	exec 'webmake --ext=coffee src/index.coffee script/index.js', ->
		console.log "yeah"