{spawn,exec} = require 'child_process'
{readFile,writeFile} = require 'fs'

launch = (cmd, options=[], callback) ->
	app = spawn cmd, options, (err) ->
		console.log err
	app.stdout.pipe(process.stdout)
	app.stderr.pipe(process.stderr)
	app.on 'exit', (status) -> callback?() if status is 0

launch2 = (cmd, callback) ->
	[x,y...] = cmd.split(' ')
	launch x,y,callback


task 'sbuild', 'ho!', ->
	exec 'webmake --ext=coffee src/index.coffee script/index.js', (args...) ->
		console.log args...
		readFile 'script/index.js', (err,data) ->
			if err
				console.log err
				return

			data = "this[\"global\"] = this;\n" + data
			writeFile 'script/index.js', data, (err) ->
			if err
				console.log err
				return

				console.log "yeah"